name: Terraform Plan

on:
  pull_request:
    branches:
      - example-staging
      - master

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/example-staging" ]; then
            source env/example-staging-uk
          else
            source env/example-production-uk
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          source .env
          terraform init -backend-config="bucket=${S3_BUCKET}" -backend-config="key=${TF_VAR_project_name}_${ENVIRONMENT}.tfstate"

      - name: Terraform Plan
        run: |
          source .env
          terraform plan -out=plan.out

      - name: Upload Plan Output
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: plan.out