name: Terraform Apply (Manual Approval)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to deploy'
        required: true
        type: choice
        options:
          - example-staging
          - master

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'eu-west-2'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load Environment Variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "example-staging" ]; then
            source env/example-staging-uk
          else
            source env/example-production-uk
          fi

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          source .env
          terraform init -backend-config="bucket=${S3_BUCKET}" -backend-config="key=${TF_VAR_project_name}_${github.event.inputs.environment}.tfstate"

      - name: Download Plan Output
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: |
          source .env
          terraform apply "plan.out"